### ISSUE TITLE
Change behavior of advanced sent page

### ISSUE THREAD

**Issue by mauricio1802** [fibercrypto/FiberCryptoWallet#121]
Change behavior of advanced send page to let me choose first one wallet, late multiple addresses of that wallet, and late multiple unespent outputs of that addresses
![Screenshot from 2019-09-06 16-49-18](https://user-images.githubusercontent.com/47878029/64459717-92697e80-d0c6-11e9-9d9a-cfc6c67f82bd.png)

**Comment by stdevCrow** [comment]
Need to add support for multi-address selection.
