### ISSUE TITLE
Need asynchronous network operations and a busy indicator in the UI

### ISSUE THREAD

**Issue by stdevCrow** [fibercrypto/FiberCryptoWallet#124]
**Feature description**
Networking operations are hanging the UI. We need asynchronous networking and a busy indicator to inform the user that a operation is being done in the backend.

**Possible implementation**
- [x] Do the networking asynchronously (everybody)
- [x] Add a boolean property `busy` to all objects that perform such asynchronously operations (everybody)
- [x] Tell the user that an operation is being done in the backend (@lateo96)

**Comment by stdevCrow** [comment]
This is not working *as expected*... so I will reopen it.

**Everyone involved (Wallets model, Outputs, Pending Transactions, etc...):**
**Check this:**
*About asynchronous operations:*
therecipe/qt#840
https://github.com/therecipe/examples/blob/40390d02efe954eb840b680dd2d4ae48a27e1453/advanced/widgets/goroutine/main.go#L48

**Comment by olemis** [comment]
what's the status of this ?

**Comment by stdevMac** [comment]
@stdevCrow take a look here :point_right:  https://github.com/fibercrypto/fibercryptowallet/pull/281/files# and see.

**Comment by stdevMac** [comment]
I made a gorutine for update wallet and resources, I think this is the way, what do you think?

**Comment by stdevMac** [comment]
Already solved [here](https://github.com/fibercrypto/fibercryptowallet/pull/306)
