### ISSUE TITLE
A DARK (night) theme

### ISSUE THREAD

**Issue by stdevCrow** [fibercrypto/FiberCryptoWallet#129]
**Description**
Dark version of the current Light Material Theme, to take care of our eyes.

- [ ] Add a button to switch the theme at runtime, mainly for prototyping
- [ ] Setup colors that match the night theme as well
- [ ] Add a color selector to select an accent color for the Material theme

**Comment by olemis** [comment]
@stdevCrow are these themes added in FiberCrypto styles repository ? is there a dark theme ?
