### ISSUE TITLE
Handle application configuration using `QSettings`

### ISSUE THREAD

**Issue by stdevCrow** [fibercrypto/FiberCryptoWallet#135]
**Description**
We are using JSON format to save/restore configuration, while using `QSettings` is a better approach.

**Advantages over the JSON approach**
- Uses the standard configuration format for every system the application runs on.
  - Windows: System registry
  - Darwin: Property list files
  - UNIX: In absence of an standard, uses INI text files
- Creating and destroying `QSettings` objects is very fast
- It ensures that the location is **always** writable
- The location and storage format is transparent for the developer
- Each developer can save/load its own settings with two lines of code without affecting others or making a bigger implementation
- There is an equivalent QML component named `Settings` that allows to write and read settings directly from QML

*See `QSettings` and `Settings` in Qt Docs for details*

**How to use it?**

Read configurations when necessary:

```c++
QSettings settings;

int value1 = settings.value("cipher/someInteger").toInt();
QString value2 = settings.value("cipher/someString").toString();
```

And write/update configurations when necessary:

```c++
QSettings settings;

int value1 = 5;
QString value2 = "bla bla bla";
settings.setValue("cipher/someInteger", value1);
settings.setValue("cipher/someString", value2);
```

In the above examples, "cipher" it's just a group of properties, like a folder.
You can name your group (if any) as you want.

**Comment by olemis** [comment]
This needs be reopened so as to fix errors on Travis Windows builds
