### ISSUE TITLE
Add ticker CalculatedHour to disambiguate between coinHours and calculatedHours in GetCoins method.

### ISSUE THREAD

**Issue by AntiD2ta** [fibercrypto/FiberCryptoWallet#140]
**Feature description**

To get the coins and coinHours in the app from a SkycoinTransactionOutput we call GetCoins with a Ticker that describe the type of value that is needed. Actually, the value calculatedHours is also needed from a output, but there is no way to get it from the implemented interfaces.

**Is your feature request related to a problem? Please describe.**
Where coinHours is requested it displays calculatedHours, this is a error.

**Describe the solution you'd like**
Add a Ticker named CalculatedHour and update GetCoins method.

**Possible implementation**

- [x] Add Ticker CalculatedHour in src/coin/skycoin/models/wallet.go.
- [x] Add a option to the ticker CalculatedHour and return the properly property
- [x] Fix option with Ticker CoinHour to return coinHours.
- [x] Finally review all the code to use the correct ticker in properly locations.

**Comment by olemis** [comment]
@stdevAntiD2ta I guess this needs an extra step consisting in reviewing the code so as to use correct ticker at every location in code .
