### ISSUE TITLE
Internationalization for UI messages

### ISSUE THREAD

**Issue by olemis** [fibercrypto/FiberCryptoWallet#147]
**Feature description**

Multiple languages in user interface.

**Is your feature request related to a problem? Please describe.**
Only English messages rendered in wallet UI , which could be a barrier for new users.

**Describe the solution you'd like**
A way to switch from one language to the other . Default to the language configured in OS

**Describe alternatives you've considered**
Native QT tooling should be preferred over golang-specific solutions e.g. [nicksnyder/go-i18n](https://github.com/nicksnyder/go-i18n) , [maximilien/i18n4go](https://github.com/maximilien/i18n4go), [GNU gettext](https://siongui.github.io/2016/01/08/golang-i18n-go-application-by-gnu-gettext/), `golang.org/x/text` , or alike.

**Additional context**
Reference QT i18n tools are [`tr()`](https://doc.qt.io/qt-5/i18n-source-translation.html) and [`qsTr`](https://doc.qt.io/qt-5/qtquick-internationalization.html#) . [QT Linguist](https://doc.qt.io/archives/qt-4.8/linguist-translators.html) has [`lupdate` tool](https://doc.qt.io/archives/qt-4.8/linguist-manager.html#lupdate) which extracts potential i18n strings from `tr()` and `qsTr()` calls in code using static analysis, as well as [`lrelease()` tool](https://doc.qt.io/archives/qt-4.8/linguist-manager.html#lrelease) for compiling TS files into QM equivalents.

**Possible implementation**

- [ ] Detect OS language and change GUI texts accordingly
- [ ] Language switch UI control including `default` option to fall back o OS language.
- [ ] Store as QT configuration option
- [ ] Implement global `tr()` function for language-specific string lookup (English pass-through)
- [ ] Wrap inline strings with a call to `tr()` function .
- [ ] Translations repositories for Spanish, French
- [ ] `Makefile` rules for i18n tasks e.g. new language, update language , compile , bundle in resources , ...
- [ ] Transifex integration

@stdevCrow open question: How would string extraction work for golang code?

**Comment by stdevCrow** [comment]
Actually this is the same as #17, so an update will be more appropriate

**Comment by stdevCrow** [comment]
Closed as duplicated (see #17 )
