### ISSUE TITLE
Spend in single transaction outputs managed by multiple wallets

### ISSUE THREAD

**Issue by olemis** [fibercrypto/FiberCryptoWallet#150]
**Feature description**

It should be possible to spend outputs no matter where them found.

**Is your feature request related to a problem? Please describe.**
It's impossible to aggregate funds kept in multiple wallets for spending in a single transaction even if private keys are well known .

**Describe the solution you'd like**
Support for multiple address and wallet selection in advanced spend GUI

**Describe alternatives you've considered**
At present only a single wallet can be chosen .

**Additional context**
This requires support for partial signing of SkyFiber transactions, documented in #138 .

**Possible implementation**

- [x] Multiple wallet selection in advanced spend GUI
- [ ] Connect wallet selection GUI with backend via QT models
- [x] If transaction spawns across multiple wallets iterate over available strategies for partial signing
- [ ] Ensure that transaction is fully signed at the end of the process 
- [x] UXID array lookup IDs for signing support #<NUMBER> relative to transaction array
- [x] UXID array lookup IDs for signing support absolute <UXID>
- [x] Add BlockchainTransactionAPI interface for creating multi-wallet transactions
- [x] Add BlockchainSignService interface for signing multi-wallet transactions
- [x] New altcoin plugin entry points for instantiating aforementioned API's
- [x] Tests for multi-wallet interfaces
- [ ] GUI component for signing progress and password input

**Comment by olemis** [comment]
This needs be implemented in GUI as well as backend . @stdevMauricio1802 shall we reopen this

**Comment by olemis** [comment]
Even if initial support in GUI looks like ready , this needs more work in backend and QT models

**Comment by mauricio1802** [comment]
The transactions are not being signed and broadcasted, an error is happening when trying to cast to core.PasswordReader in signTxn method

**Comment by olemis** [comment]
@stdevMauricio1802 shouldn't it fail at compile time ?
