### ISSUE TITLE
pip-installable package 

### ISSUE THREAD

**Issue by olemis** [fibercrypto/FiberCryptoWallet#16]
**Describe the solution you'd like**

- [ ] Build files through `setup.py` that can be published for distribution in PyPI
- [ ] Test them in PyPI test sandbox

**Comment by stdevCrow** [comment]
For this we need the backend, no?
I mean. QML only describes the UI, you can't program so far application logic in QML, we need to use another language, Python in this case. The application is not functional at all at this point, so building a package has no sense yet.

**Comment by stdevCrow** [comment]
Not needed as the backend changed to Go.
