### ISSUE TITLE
Fix scrolling issues

### ISSUE THREAD

**Issue by stdevCrow** [fibercrypto/FiberCryptoWallet#162]
**Describe the bug**
Some scroll views do not scroll to the end of its content when requested.

**Environment information:**

Not necessary.

**Steps to Reproduce**

1. Go to 'Send' tab (for example)
2.  Create a transaction
3. See the outputs
4. Try to scroll to the end

**Actual behavior**
When you scroll down the content is not show entirely.

**Expected behavior**
The content must be entirely scrollable.

**Comment by olemis** [comment]
@stdevMac pls take a look

**Comment by stdevCrow** [comment]
This is not done yet?
