### ISSUE TITLE
Restore Windows on Travis build matrix

### ISSUE THREAD

**Issue by olemis** [fibercrypto/FiberCryptoWallet#183]
**Describe the bug**
Windows disabled on Travis .

**Environment information:**

- OS: Windows
- Platform: see [Travis worker info](https://travis-ci.org/fibercrypto/FiberCryptoWallet/jobs/603626557#L1-L6)

**Steps to Reproduce**
According to Travis output steps should be.

- Checkout repository source code
- Ensure `Chocolatey` is installed
- Run `choco install make -y`
- Run `make install-deps-Windows`
- Run `make install-linters`
- Run `make lint`
- Run `make build`
- Run `make test`

**Actual behavior**
Build and test steps [fail with message](https://travis-ci.org/fibercrypto/FiberCryptoWallet/jobs/603432965#L315-L319)

```
vendor\golang.org\x\sys\windows\dll_windows.go:21:6: missing function body
vendor\golang.org\x\sys\windows\dll_windows.go:24:6: missing function body
```

**Expected behavior**
Successful build and test run.

**Additional context**
The aforementioned error showed up after applying changes in #182 for #138 and led to removing Windows from matrix build so as to move forward with project development

**Possible implementation**
No clue about neither the error nor requiured solution.

**Comment by olemis** [comment]
@olemis could someone please take a look into this ?

**Comment by stdevMac** [comment]
@olemis Me

**Comment by stdevMac** [comment]
Already solved [here](https://github.com/fibercrypto/FiberCryptoWallet/pull/161)
