### ISSUE TITLE
Initialize repository

### ISSUE THREAD

**Issue by olemis** [fibercrypto/FiberCryptoWallet#2]
**Feature description**

Initialize source code version control repository.

**Describe the solution you'd like**
Initial (unfinished) code with tests.

**Describe alternatives you've considered**
Appveyor for Windows CI builds

**Possible implementation**

- ~Make targets~ QT relies on `cmake`
- [x] Concise README
- [x] Empty CHANGELOG
- [x] Travis build matrix for linux and osx
- [x] Travis notifications for Telegram bot
- [x] Setup build env
- [x] Setup Github templates

**Comment by stdevCrow** [comment]
Qt's build system generates the Makefile automatically. That must be true even with PySide2 projects. I will check it anyway.

**Comment by stdevCrow** [comment]
Apparently PySide2 uses CMake as build system.
