### ISSUE TITLE
Check for error if any after signing a transaction in QML

### ISSUE THREAD

**Issue by stdevAlDen** [fibercrypto/FiberCryptoWallet#228]
**Describe the bug**
There is a possibility to send invalid transactions to the network even if this can be determined with the app.

**Environment information:**
Any
**Steps to Reproduce**

1. Go to [walletManager.signTxn](https://github.com/fibercrypto/FiberCryptoWallet/blob/2acfe5ec73c10fb8c64830e2f049bb340d484165/src/ui/PageSend.qml#L180)

**Actual behavior**
No checking for error after signing a transaction.

**Expected behavior**
Should check if there is any error from `walletManager.signTxn` before calling `walletManager.broadcastTxn`.

**Possible implementation**
Reasearch...

**Comment by stdevMac** [comment]
Already solved in develop @stdevAlDen
