### ISSUE TITLE
Create-Load Wallet on Start not working 

### ISSUE THREAD

**Issue by stdevMac** [fibercrypto/FiberCryptoWallet#252]
**Describe the bug**
When we create or load a wallet, If we don't have any wallet created, and we create one, when the wallets page load, in the first try we don't get see the wallet.
If we restart the app, then we load the wallet.
Searching in the code, in the part of we should call the function for create the wallet. we don't create Encrypted wallets, this should solve here too

**Environment information:**

- OS: e.g. All

**Steps to Reproduce**

2. Run '....'
3. Write data to '....'

**Actual behavior**
Explain the failure modes and effects, everything indicating the existence of the bug.

**Expected behavior**
Once we create the wallet. we get the wallet on the screen

**Possible implementation**
This is probably caused in the way we load the wallets
[ ] Load the wallets in the moment of creation
[ ] Create encrypted wallets in the main Page

**Comment by olemis** [comment]
@stdevMac pls add to milestone:0.27.0
