### ISSUE TITLE
Migrate Skycoin vendor reference

### ISSUE THREAD

**Issue by olemis** [fibercrypto/FiberCryptoWallet#272]
**Is your feature request related to a problem? Please describe.**
Officlal Skycoin repository is no longer `skycoin/skycoin` but that's the one still in use in `vendor`.

**Describe the solution you'd like**
- [ ] Switch to `SkycoinProject/skycoin`
- [ ] Ckeckout `0.27.0` tag

**Comment by m4yk3ldev** [comment]
@olemis Ok
