### ISSUE TITLE
App Crash when a wallet is created

### ISSUE THREAD

**Issue by mauricio1802** [fibercrypto/FiberCryptoWallet#275]
**Describe the bug**
The app crash when i try to create a wallet

**Environment information:**

- OS: Linux
- Platform: Linux 4.15.0-66-generic x86_64**Steps to Reproduce**

1. Open the app
2. Create a wallet
3. App crash

**Actual behavior**
I try to add a wallet of any type and the app crash after i press create button

**Expected behavior**
When i press create button i expect that the new wallet be listed in the main page

**Comment by olemis** [comment]
@stdevMauricio1802 wasn't this already reported ?

**Comment by mauricio1802** [comment]
@olemis  the previous report was about create a deterministic wallet and a bip44 wallet with the same seed
