### ISSUE TITLE
Unable to sign transaction

### ISSUE THREAD

**Issue by stdevAlDen** [fibercrypto/FiberCryptoWallet#278]
**Describe the bug**
Type assertion failed, function (`(func(string, core.KeyValueStore) (string, error))`) does not implement [`core.PaswordReader`](https://github.com/fibercrypto/fibercryptowallet/blob/ae8106c46568392e4c73f75aa216724e9dc691e4/src/core/textutil.go#L4)

**Environment information:**

- OS: any
- Platform: any

**Steps to Reproduce**
Just read the source code.

1. Asserting for core.Password reader [here](https://github.com/fibercrypto/fibercryptowallet/blob/ae8106c46568392e4c73f75aa216724e9dc691e4/src/models/walletsManager.go#L575).
2. Type [function](https://github.com/fibercrypto/fibercryptowallet/blob/ae8106c46568392e4c73f75aa216724e9dc691e4/src/models/walletsManager.go#L645) does not implement `core.PasswordReader`.

**Actual behavior**
Trying to sign a transaction does not work.

**Expected behavior**
Should be able to sign a transaction.

**Comment by stdevMac** [comment]
@stdevAlDen When I try to send a transaction in my machine the wallet does nothing, not send the coins and not crash the app

**Comment by stdevAlDen** [comment]
@stdevMac consider this fix: https://github.com/simelo/fibercryptowallet/commit/ded474d45485131b3a493060c6e6df8144731906

**Comment by stdevAlDen** [comment]
@stdevMac consider this fix: https://github.com/simelo/fibercryptowallet/commit/ded474d45485131b3a493060c6e6df8144731906
