### ISSUE TITLE
Repo name no updated in project after being changed

### ISSUE THREAD

**Issue by AntiD2ta** [fibercrypto/FiberCryptoWallet#286]
**Describe the bug**
The repository name was changed and references to it were not updated, this causes some errors.

**Steps to Reproduce**
1. Run `grep -nr "FiberCryptoWallet"` in the cli from the project's root directory
2. You should see severals matches.

**Actual behavior**
Currently, the wallet can't be opened in Linux nor Windows environment because the makefile is not updated.

**Expected behavior**
All should work as before changing the name.

**Possible implementation**
Replace `FiberCryptoWallet` for `fibercryptowallet` in code.

**Comment by olemis** [comment]
@stdevAntiD2ta is there a PR I can review for this ?
