### ISSUE TITLE
Crash when outputs view opened

### ISSUE THREAD

**Issue by AntiD2ta** [fibercrypto/FiberCryptoWallet#302]
**Describe the bug**
Crash when outputs view opened.

**Steps to Reproduce**
1. Run the wallet offline or with local data not updated
2. Go for outputs
3. See error(app terminates with panic)(SIGSEGV)

**Actual behavior**
App crashes when outputs view opened and app is not synchronized or without connection.

**Expected behavior**
A busy indicator if it the data is being getted or show no data if there is no outputs in wallets.

**Possible implementation**
Catch the error, log it, and display a busy indicator if the request for outputs to API fails.

**Comment by stdevMac** [comment]
@stdevAntiD2ta Should solved in develop
