### ISSUE TITLE
Add minimal travis-ci for project

### ISSUE THREAD

**Issue by stdevMac** [fibercrypto/FiberCryptoWallet#66]
Setup some basic ci/cd for the project

Cause in other project we use `travis-ci` this can be an option

This must:
- [x] Run Basic test in `ci`
- [x] Work in linux
- [x] Work in MacOs

**Comment by stdevMac** [comment]
Duplicated of #2

**Comment by stdevCrow** [comment]
Indeed, this should be closed and the work should reference issue #2

**Comment by olemis** [comment]
>  this should be closed and the work should reference issue #2

👍
