### ISSUE TITLE
Notify when there are wallets available in the models

### ISSUE THREAD

**Issue by stdevCrow** [fibercrypto/FiberCryptoWallet#69]
**Description**
We need to know when are wallets available. But the model that informs that is currently created in the wallets page, and, for saving resources, that page is not created at startup. Instead I replace the initial page when the user requests so (now, by clicking ***Create*** or ***Load***). The same is applied to the `Blockchain`, `Networking`, etc. pages. Saving memory is critical in this application because we want to use it on embedded and mobile systems, so creating pages statically and retain them in memory is not an option. Right now the memory consumption is about ~50 MB, and should not be greater than that.

**Possible implementation**
We need a **lightweight** backend model, maybe named `StartupModel` or `SetupModel` (I like the last one) that load the minimal required information that we require to setup the application properly.
That model can be instantiated inside `GeneralStackView`.
Initially, that model should have a property `walletsCount` that we can use to skip the Create/Load Wallet Page.
New properties can be added over time as needed.

**Comment by stdevCrow** [comment]
Updated description, take a look at this @stdevMauricio1802

**Comment by olemis** [comment]
fixed in dc8422c
